/*
 * Minimal nrf_802154 config for variant C spike (no OpenThread).
 */

#ifndef PLATFORM_CONFIG_SPIKE_H_
#define PLATFORM_CONFIG_SPIKE_H_

#define NRF_802154_CSMA_CA_ENABLED           1
#define NRF_802154_ACK_TIMEOUT_ENABLED       1
#define NRF_802154_TX_STARTED_NOTIFY_ENABLED 1
#define NRF_802154_SECURITY_WRITER_ENABLED   0
#define NRF_802154_ENCRYPTION_ENABLED        0
#define PLATFORM_FEM_ENABLE_DEFAULT_CONFIG   0

#define NRF_802154_PENDING_SHORT_ADDRESSES     8
#define NRF_802154_PENDING_EXTENDED_ADDRESSES  8

/* Required by nrf_802154_delayed_trx.c when SL_OPENSOURCE=OFF */
#define NRF_CONFIG_CPU_FREQ_MHZ 128

#endif /* PLATFORM_CONFIG_SPIKE_H_ */
